# Generated by Django 5.0.6 on 2025-04-26 12:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fakultet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomi', models.CharField(max_length=255)),
                ('yaratilgan_sana', models.DateField()),
                ('dekan', models.CharField(max_length=255)),
                ('zam_dekan', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Stipendiya',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomi', models.CharField(max_length=255)),
                ('puli', models.DecimalField(decimal_places=2, max_digits=10)),
                ('muddati', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='TalimShakli',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomi', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='TalimTuri',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('turi', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Ustoz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ism', models.CharField(max_length=255)),
                ('familiya', models.CharField(max_length=255)),
                ('mutaxassislik', models.CharField(max_length=255)),
                ('yosh', models.PositiveIntegerField()),
                ('daraja', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Guruh',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomi', models.CharField(max_length=100)),
                ('turi', models.CharField(max_length=100)),
                ('fakultet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='datas.fakultet')),
            ],
        ),
        migrations.CreateModel(
            name='Talaba',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ism', models.CharField(max_length=255)),
                ('familiya', models.CharField(max_length=255)),
                ('tugilgan_kun', models.DateField()),
                ('rasm', models.ImageField(blank=True, null=True, upload_to='talaba_rasm/')),
                ('telefon', models.CharField(max_length=20)),
                ('fakultet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='datas.fakultet')),
                ('guruh', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='datas.guruh')),
                ('nomdor_stipendiya', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='datas.stipendiya')),
                ('talim_shakli', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='datas.talimshakli')),
                ('talim_turi', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='datas.talimturi')),
            ],
        ),
        migrations.CreateModel(
            name='IlmiyFaoliyat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomi', models.CharField(max_length=255)),
                ('turi', models.CharField(max_length=255)),
                ('sanasi', models.DateField()),
                ('izoh', models.TextField()),
                ('natija', models.TextField()),
                ('holati', models.CharField(max_length=255)),
                ('moliyaviy_manba', models.CharField(max_length=255)),
                ('tadqiqot_joyi', models.CharField(max_length=255)),
                ('ishtirokchilar', models.ManyToManyField(related_name='ilmiy_faoliyatlar', to='datas.talaba')),
                ('rahbar', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='datas.ustoz')),
            ],
        ),
    ]
